export const languageList = [
    { languageName: 'Afrikaans', code: 'Afrikaans', isoCode: 'af' },
    { languageName: 'Arabic', code: 'Arabic', isoCode: 'ar' },
    { languageName: 'Armenian', code: 'Armenian', isoCode: 'hy' },
    { languageName: 'Azerbaijani', code: 'Azerbaijani', isoCode: 'az' },
    { languageName: 'Belarusian', code: 'Belarusian', isoCode: 'be' },
    { languageName: 'Bengali', code: 'Bengali', isoCode: 'bn' },
    { languageName: 'Bosnian', code: 'Bosnian', isoCode: 'bs' },
    { languageName: 'Bulgarian', code: 'Bulgarian', isoCode: 'bg' },
    { languageName: 'Catalan', code: 'Catalan', isoCode: 'ca' },
    { languageName: 'Chinese', code: 'Chinese', isoCode: 'zh' },
    { languageName: 'Croatian', code: 'Croatian', isoCode: 'hr' },
    { languageName: 'Czech', code: 'Czech', isoCode: 'cs' },
    { languageName: 'Danish', code: 'Danish', isoCode: 'da' },
    { languageName: 'Dutch', code: 'Dutch', isoCode: 'nl' },
    { languageName: 'English', code: 'English', isoCode: 'en' },
    { languageName: 'Estonian', code: 'Estonian', isoCode: 'et' },
    { languageName: 'Finnish', code: 'Finnish', isoCode: 'fi' },
    { languageName: 'French', code: 'French', isoCode: 'fr' },
    { languageName: 'Galician', code: 'Galician', isoCode: 'gl' },
    { languageName: 'German', code: 'German', isoCode: 'de' },
    { languageName: 'Greek', code: 'Greek', isoCode: 'el' },
    { languageName: 'Hebrew', code: 'Hebrew', isoCode: 'he' },
    { languageName: 'Hindi', code: 'Hindi', isoCode: 'hi' },
    { languageName: 'Hungarian', code: 'Hungarian', isoCode: 'hu' },
    { languageName: 'Icelandic', code: 'Icelandic', isoCode: 'is' },
    { languageName: 'Indonesian', code: 'Indonesian', isoCode: 'id' },
    { languageName: 'Italian', code: 'Italian', isoCode: 'it' },
    { languageName: 'Japanese', code: 'Japanese', isoCode: 'ja' },
    { languageName: 'Kannada', code: 'Kannada', isoCode: 'kn' },
    { languageName: 'Kazakh', code: 'Kazakh', isoCode: 'kk' },
    { languageName: 'Korean', code: 'Korean', isoCode: 'ko' },
    { languageName: 'Latvian', code: 'Latvian', isoCode: 'lv' },
    { languageName: 'Lithuanian', code: 'Lithuanian', isoCode: 'lt' },
    { languageName: 'Macedonian', code: 'Macedonian', isoCode: 'mk' },
    { languageName: 'Malay', code: 'Malay', isoCode: 'ms' },
    { languageName: 'Marathi', code: 'Marathi', isoCode: 'mr' },
    { languageName: 'Maori', code: 'Maori', isoCode: 'mi' },
    { languageName: 'Nepali', code: 'Nepali', isoCode: 'ne' },
    { languageName: 'Norwegian', code: 'Norwegian', isoCode: 'no' },
    { languageName: 'Persian', code: 'Persian', isoCode: 'fa' },
    { languageName: 'Polish', code: 'Polish', isoCode: 'pl' },
    { languageName: 'Portuguese', code: 'Portuguese', isoCode: 'pt' },
    { languageName: 'Romanian', code: 'Romanian', isoCode: 'ro' },
    { languageName: 'Russian', code: 'Russian', isoCode: 'ru' },
    { languageName: 'Serbian', code: 'Serbian', isoCode: 'sr' },
    { languageName: 'Slovak', code: 'Slovak', isoCode: 'sk' },
    { languageName: 'Slovenian', code: 'Slovenian', isoCode: 'sl' },
    { languageName: 'Spanish', code: 'Spanish', isoCode: 'es' },
    { languageName: 'Swahili', code: 'Swahili', isoCode: 'sw' },
    { languageName: 'Swedish', code: 'Swedish', isoCode: 'sv' },
    { languageName: 'Tagalog', code: 'Tagalog', isoCode: 'tl' },
    { languageName: 'Tamil', code: 'Tamil', isoCode: 'ta' },
    { languageName: 'Thai', code: 'Thai', isoCode: 'th' },
    { languageName: 'Turkish', code: 'Turkish', isoCode: 'tr' },
    { languageName: 'Ukrainian', code: 'Ukrainian', isoCode: 'uk' },
    { languageName: 'Urdu', code: 'Urdu', isoCode: 'ur' },
    { languageName: 'Vietnamese', code: 'Vietnamese', isoCode: 'vi' },
    { languageName: 'Welsh', code: 'Welsh', isoCode: 'cy' },
]

export const getLanguageISOCodeByName = (languageName: string): string | undefined => {
    return languageList.find(language => language.languageName === languageName)?.isoCode
}

export const getLanguageNameByISOCode = (isoCode: string): string => {
    return languageList.find(language => language.isoCode === isoCode)?.languageName ?? 'Unknown Lang.'
}

